services:
  product:
    build: product-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_FILE_NAME=/app/logs/product-service.log
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_PATTERN_FILE=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    volumes:
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy

  # recommendation:
  #   build: microservices/recommendation-service
  #   mem_limit: 512m
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy

  review:
    build: review-service
    mem_limit: 512m
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_FILE_NAME=/app/logs/review-service.log
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_PATTERN_FILE=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy

  product-composite:
    build: product-composite-service
    mem_limit: 512m
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_FILE_NAME=/app/logs/product-composite-service.log
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_PATTERN_FILE=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    volumes:
      - ./logs:/app/logs

  mongodb:
    image: mongo:6.0.4
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - ./logs:/var/log/mongodb
    healthcheck:
      test: "mongostat -n 1"
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:8.0.32
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./logs:/var/log/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
