
# Default application configuration
server:
  port: 7003
  error:
    include-message: always

# MySQL configuration (for local development)
spring:
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update  # Strongly recommend to set this property to "none" in a production environment!

# Logging configuration
logging:
  level:
    root: INFO
    "[com.ragav.ecommerce]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE

---
# Profile-specific configuration for Docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080